// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pots.Infrastructure;

#nullable disable

namespace Pots.Infrastructure.Migrations
{
    [DbContext(typeof(PotsDbContext))]
    [Migration("20260520111146_AddPatientUserEmailsFunction")]
    partial class AddPatientUserEmailsFunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pots.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_actor_user_id_created_at");

                    b.HasIndex("PatientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_patient_id_created_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.CaregiverNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("pk_caregiver_notes");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_caregiver_notes_author_user_id");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_caregiver_notes_deleted_by_user_id");

                    b.HasIndex("PatientId", "CreatedAt")
                        .HasDatabaseName("ix_caregiver_notes_patient_created");

                    b.ToTable("caregiver_notes", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.DailyStatusEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EpisodeOccurred")
                        .HasColumnType("boolean")
                        .HasColumnName("episode_occurred");

                    b.Property<string>("LocationNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_note");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Posture")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("posture");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_daily_status_entries");

                    b.HasIndex("RecordedByUserId")
                        .HasDatabaseName("ix_daily_status_entries_recorded_by_user_id");

                    b.HasIndex("PatientId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_daily_status_entries_patient_id_created_at");

                    b.ToTable("daily_status_entries", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_taken");

                    b.Property<int?>("BpDuringDiastolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_during_diastolic");

                    b.Property<int?>("BpDuringSystolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_during_systolic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int?>("HrDuringBpm")
                        .HasColumnType("integer")
                        .HasColumnName("hr_during_bpm");

                    b.Property<string>("MainSymptom")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("main_symptom");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PostureBefore")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("posture_before");

                    b.Property<bool?>("PreventedFainting")
                        .HasColumnType("boolean")
                        .HasColumnName("prevented_fainting");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<int?>("RecoveryTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_time_minutes");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("TriggerSuspected")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("trigger_suspected");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("RecordedByUserId")
                        .HasDatabaseName("ix_episodes_recorded_by_user_id");

                    b.HasIndex("PatientId", "StartTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_episodes_patient_id_start_time");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.GrantUpgradeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_grant_upgrade_requests");

                    b.HasIndex("GrantId")
                        .IsUnique()
                        .HasDatabaseName("ix_grant_upgrade_requests_grant_one_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_grant_upgrade_requests_patient_id");

                    b.HasIndex("RequesterUserId")
                        .HasDatabaseName("ix_grant_upgrade_requests_requester_user_id");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("ix_grant_upgrade_requests_resolved_by_user_id");

                    b.ToTable("grant_upgrade_requests", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.MagicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_magic_link_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_magic_link_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_magic_link_tokens_token_hash");

                    b.ToTable("magic_link_tokens", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_owner_user_id");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.PatientGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("GranteeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("grantee_user_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_patient_grants");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_patient_grants_granted_by_user_id");

                    b.HasIndex("GranteeUserId")
                        .HasDatabaseName("ix_patient_grants_grantee_user_id");

                    b.HasIndex("RevokedByUserId")
                        .HasDatabaseName("ix_patient_grants_revoked_by_user_id");

                    b.HasIndex("PatientId", "GranteeUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_grants_patient_id_grantee_user_id")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("patient_grants", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.PatientTargets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CompressionGoalHoursPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("compression_goal_hours_per_day");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExercisePlanNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("exercise_plan_note");

                    b.Property<int>("HydrationTargetMl")
                        .HasColumnType("integer")
                        .HasColumnName("hydration_target_ml");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SaltClinicianAttestation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("salt_clinician_attestation");

                    b.Property<bool>("SaltTargetEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("salt_target_enabled");

                    b.Property<int?>("SaltTargetMg")
                        .HasColumnType("integer")
                        .HasColumnName("salt_target_mg");

                    b.Property<decimal?>("SleepTargetHours")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("sleep_target_hours");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_targets");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_targets_patient_id");

                    b.ToTable("patient_targets", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.PreventiveActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AbdominalCompression")
                        .HasColumnType("boolean")
                        .HasColumnName("abdominal_compression");

                    b.Property<bool>("AdequateProtein")
                        .HasColumnType("boolean")
                        .HasColumnName("adequate_protein");

                    b.Property<bool>("AlcoholAvoided")
                        .HasColumnType("boolean")
                        .HasColumnName("alcohol_avoided");

                    b.Property<bool>("AvoidedHeat")
                        .HasColumnType("boolean")
                        .HasColumnName("avoided_heat");

                    b.Property<bool>("AvoidedHotBathSauna")
                        .HasColumnType("boolean")
                        .HasColumnName("avoided_hot_bath_sauna");

                    b.Property<bool>("AvoidedLargeHighCarbMeal")
                        .HasColumnType("boolean")
                        .HasColumnName("avoided_large_high_carb_meal");

                    b.Property<bool>("AvoidedLongStanding")
                        .HasColumnType("boolean")
                        .HasColumnName("avoided_long_standing");

                    b.Property<bool>("AvoidedOverexertion")
                        .HasColumnType("boolean")
                        .HasColumnName("avoided_overexertion");

                    b.Property<string>("CaffeineLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("caffeine_level");

                    b.Property<bool>("ColdShower")
                        .HasColumnType("boolean")
                        .HasColumnName("cold_shower");

                    b.Property<int?>("CompressionHoursWorn")
                        .HasColumnType("integer")
                        .HasColumnName("compression_hours_worn");

                    b.Property<bool>("CompressionSocks")
                        .HasColumnType("boolean")
                        .HasColumnName("compression_socks");

                    b.Property<bool>("ConsistentBedtimes")
                        .HasColumnType("boolean")
                        .HasColumnName("consistent_bedtimes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<bool>("ElectrolyteTaken")
                        .HasColumnType("boolean")
                        .HasColumnName("electrolyte_taken");

                    b.Property<int?>("ExerciseDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_duration_minutes");

                    b.Property<string>("ExerciseIntensity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exercise_intensity");

                    b.Property<int?>("FluidMl")
                        .HasColumnType("integer")
                        .HasColumnName("fluid_ml");

                    b.Property<bool>("MedicationTakenAsPrescribed")
                        .HasColumnType("boolean")
                        .HasColumnName("medication_taken_as_prescribed");

                    b.Property<bool>("MissedDose")
                        .HasColumnType("boolean")
                        .HasColumnName("missed_dose");

                    b.Property<string>("MobilityAid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mobility_aid");

                    b.Property<bool>("MorningWaterBeforeStanding")
                        .HasColumnType("boolean")
                        .HasColumnName("morning_water_before_standing");

                    b.Property<bool>("NapTaken")
                        .HasColumnType("boolean")
                        .HasColumnName("nap_taken");

                    b.Property<string>("NewMedicationOrSupplement")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("new_medication_or_supplement");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<bool>("PlannedRestBreaks")
                        .HasColumnType("boolean")
                        .HasColumnName("planned_rest_breaks");

                    b.Property<string>("PostExerciseSymptoms")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("post_exercise_symptoms");

                    b.Property<bool>("PtExercises")
                        .HasColumnType("boolean")
                        .HasColumnName("pt_exercises");

                    b.Property<bool>("RecumbentExercise")
                        .HasColumnType("boolean")
                        .HasColumnName("recumbent_exercise");

                    b.Property<bool>("RegularMeals")
                        .HasColumnType("boolean")
                        .HasColumnName("regular_meals");

                    b.Property<bool?>("RescueMedicationUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("rescue_medication_used");

                    b.Property<bool?>("SaltTargetReached")
                        .HasColumnType("boolean")
                        .HasColumnName("salt_target_reached");

                    b.Property<bool>("SatDuringShowerCooking")
                        .HasColumnType("boolean")
                        .HasColumnName("sat_during_shower_cooking");

                    b.Property<string>("SideEffects")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("side_effects");

                    b.Property<bool>("SkippedBreakfast")
                        .HasColumnType("boolean")
                        .HasColumnName("skipped_breakfast");

                    b.Property<int?>("SleepQuality")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_quality");

                    b.Property<bool>("SleptEnough")
                        .HasColumnType("boolean")
                        .HasColumnName("slept_enough");

                    b.Property<bool>("SmallFrequentMeals")
                        .HasColumnType("boolean")
                        .HasColumnName("small_frequent_meals");

                    b.Property<bool>("StayedInShadeAc")
                        .HasColumnType("boolean")
                        .HasColumnName("stayed_in_shade_ac");

                    b.Property<bool>("Strength")
                        .HasColumnType("boolean")
                        .HasColumnName("strength");

                    b.Property<bool>("Stretching")
                        .HasColumnType("boolean")
                        .HasColumnName("stretching");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrineColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("urine_color");

                    b.Property<bool>("UsedActivityPacing")
                        .HasColumnType("boolean")
                        .HasColumnName("used_activity_pacing");

                    b.Property<bool>("UsedCoolingVestFan")
                        .HasColumnType("boolean")
                        .HasColumnName("used_cooling_vest_fan");

                    b.Property<bool>("WaistHighCompression")
                        .HasColumnType("boolean")
                        .HasColumnName("waist_high_compression");

                    b.Property<bool>("Walking")
                        .HasColumnType("boolean")
                        .HasColumnName("walking");

                    b.Property<bool?>("WokeRefreshed")
                        .HasColumnType("boolean")
                        .HasColumnName("woke_refreshed");

                    b.HasKey("Id")
                        .HasName("pk_preventive_action_logs");

                    b.HasIndex("PatientId", "Day")
                        .IsUnique()
                        .HasDatabaseName("ix_preventive_action_logs_patient_id_day");

                    b.ToTable("preventive_action_logs", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.SymptomLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AbdominalPain")
                        .HasColumnType("integer")
                        .HasColumnName("abdominal_pain");

                    b.Property<int?>("AbilityToWalk")
                        .HasColumnType("integer")
                        .HasColumnName("ability_to_walk");

                    b.Property<int?>("AbilityToWork")
                        .HasColumnType("integer")
                        .HasColumnName("ability_to_work");

                    b.Property<int?>("Anxiety")
                        .HasColumnType("integer")
                        .HasColumnName("anxiety");

                    b.Property<int?>("AppetiteLevel")
                        .HasColumnType("integer")
                        .HasColumnName("appetite_level");

                    b.Property<int?>("Bloating")
                        .HasColumnType("integer")
                        .HasColumnName("bloating");

                    b.Property<int?>("BloodPooling")
                        .HasColumnType("integer")
                        .HasColumnName("blood_pooling");

                    b.Property<string>("Bowel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("bowel");

                    b.Property<int?>("BrainFog")
                        .HasColumnType("integer")
                        .HasColumnName("brain_fog");

                    b.Property<int?>("ChestDiscomfort")
                        .HasColumnType("integer")
                        .HasColumnName("chest_discomfort");

                    b.Property<int?>("Chills")
                        .HasColumnType("integer")
                        .HasColumnName("chills");

                    b.Property<int?>("ColdExtremities")
                        .HasColumnType("integer")
                        .HasColumnName("cold_extremities");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Dizziness")
                        .HasColumnType("integer")
                        .HasColumnName("dizziness");

                    b.Property<bool>("FaintingEpisode")
                        .HasColumnType("boolean")
                        .HasColumnName("fainting_episode");

                    b.Property<int?>("Fatigue")
                        .HasColumnType("integer")
                        .HasColumnName("fatigue");

                    b.Property<int?>("Flushing")
                        .HasColumnType("integer")
                        .HasColumnName("flushing");

                    b.Property<int?>("Headache")
                        .HasColumnType("integer")
                        .HasColumnName("headache");

                    b.Property<int?>("HeatIntolerance")
                        .HasColumnType("integer")
                        .HasColumnName("heat_intolerance");

                    b.Property<int?>("Mood")
                        .HasColumnType("integer")
                        .HasColumnName("mood");

                    b.Property<int?>("Nausea")
                        .HasColumnType("integer")
                        .HasColumnName("nausea");

                    b.Property<int?>("NearFainting")
                        .HasColumnType("integer")
                        .HasColumnName("near_fainting");

                    b.Property<int?>("Palpitations")
                        .HasColumnType("integer")
                        .HasColumnName("palpitations");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("ShortnessOfBreath")
                        .HasColumnType("integer")
                        .HasColumnName("shortness_of_breath");

                    b.Property<int?>("Sleepiness")
                        .HasColumnType("integer")
                        .HasColumnName("sleepiness");

                    b.Property<int?>("SocialTolerance")
                        .HasColumnType("integer")
                        .HasColumnName("social_tolerance");

                    b.Property<int?>("Sweating")
                        .HasColumnType("integer")
                        .HasColumnName("sweating");

                    b.Property<int?>("TachycardiaSensation")
                        .HasColumnType("integer")
                        .HasColumnName("tachycardia_sensation");

                    b.Property<int?>("Tremor")
                        .HasColumnType("integer")
                        .HasColumnName("tremor");

                    b.Property<int?>("VisualDisturbance")
                        .HasColumnType("integer")
                        .HasColumnName("visual_disturbance");

                    b.Property<int?>("Weakness")
                        .HasColumnType("integer")
                        .HasColumnName("weakness");

                    b.HasKey("Id")
                        .HasName("pk_symptom_logs");

                    b.HasIndex("PatientId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_symptom_logs_patient_id_recorded_at");

                    b.ToTable("symptom_logs", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.VitalSignLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AmbientTempC")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("ambient_temp_c");

                    b.Property<int?>("BpLyingDiastolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_lying_diastolic");

                    b.Property<int?>("BpLyingSystolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_lying_systolic");

                    b.Property<int?>("BpSittingDiastolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_sitting_diastolic");

                    b.Property<int?>("BpSittingSystolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_sitting_systolic");

                    b.Property<int?>("BpStandingDiastolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_standing_diastolic");

                    b.Property<int?>("BpStandingSystolic")
                        .HasColumnType("integer")
                        .HasColumnName("bp_standing_systolic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ExerciseMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_minutes");

                    b.Property<int?>("MenstrualCycleDay")
                        .HasColumnType("integer")
                        .HasColumnName("menstrual_cycle_day");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("RestingHrBpm")
                        .HasColumnType("integer")
                        .HasColumnName("resting_hr_bpm");

                    b.Property<int?>("SleepDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_duration_minutes");

                    b.Property<int?>("SleepQuality")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_quality");

                    b.Property<int?>("Spo2Percent")
                        .HasColumnType("integer")
                        .HasColumnName("spo2percent");

                    b.Property<int?>("StandingHrBpm10Min")
                        .HasColumnType("integer")
                        .HasColumnName("standing_hr_bpm10min");

                    b.Property<int?>("StandingHrBpm2Min")
                        .HasColumnType("integer")
                        .HasColumnName("standing_hr_bpm2min");

                    b.Property<int?>("StandingHrBpm5Min")
                        .HasColumnType("integer")
                        .HasColumnName("standing_hr_bpm5min");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer")
                        .HasColumnName("steps");

                    b.Property<int?>("TimeLyingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_lying_minutes");

                    b.Property<int?>("TimeUprightMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_upright_minutes");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_vital_sign_logs");

                    b.HasIndex("PatientId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vital_sign_logs_patient_id_recorded_at");

                    b.ToTable("vital_sign_logs", (string)null);
                });

            modelBuilder.Entity("Pots.Domain.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_users_actor_user_id");

                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_log_patients_patient_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.CaregiverNote", b =>
                {
                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_notes_users_author_user_id");

                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_caregiver_notes_users_deleted_by_user_id");

                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_notes_patients_patient_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.DailyStatusEntry", b =>
                {
                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_status_entries_patients_patient_id");

                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_status_entries_users_recorded_by_user_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.Episode", b =>
                {
                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_patients_patient_id");

                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_users_recorded_by_user_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.GrantUpgradeRequest", b =>
                {
                    b.HasOne("Pots.Domain.Entities.PatientGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grant_upgrade_requests_patient_grants_grant_id");

                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grant_upgrade_requests_patients_patient_id");

                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grant_upgrade_requests_users_requester_user_id");

                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_grant_upgrade_requests_users_resolved_by_user_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.Patient", b =>
                {
                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patients_users_owner_user_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.PatientGrant", b =>
                {
                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_grants_users_granted_by_user_id");

                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GranteeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_grants_users_grantee_user_id");

                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_grants_patients_patient_id");

                    b.HasOne("Pots.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_grants_users_revoked_by_user_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.PatientTargets", b =>
                {
                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_targets_patients_patient_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.PreventiveActionLog", b =>
                {
                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_preventive_action_logs_patients_patient_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.SymptomLog", b =>
                {
                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_symptom_logs_patients_patient_id");
                });

            modelBuilder.Entity("Pots.Domain.Entities.VitalSignLog", b =>
                {
                    b.HasOne("Pots.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vital_sign_logs_patients_patient_id");
                });
#pragma warning restore 612, 618
        }
    }
}
